//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.16 at 10:59:44 AM EDT 
//


package com.mukul.test.soap_service;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for course.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="course">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Science"/>
 *     &lt;enumeration value="Maths"/>
 *     &lt;enumeration value="Literature"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "course")
@XmlEnum
public enum Course {

    @XmlEnumValue("Science")
    SCIENCE("Science"),
    @XmlEnumValue("Maths")
    MATHS("Maths"),
    @XmlEnumValue("Literature")
    LITERATURE("Literature");
    private final String value;

    Course(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Course fromValue(String v) {
        for (Course c: Course.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
